package com.tsjy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotice<M extends BaseNotice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}

	public java.lang.String getUserid() {
		return get("userid");
	}

	public void setEnabled(java.lang.String enabled) {
		set("enabled", enabled);
	}

	public java.lang.String getEnabled() {
		return get("enabled");
	}

	public void setNoticetype(java.lang.String noticetype) {
		set("noticetype", noticetype);
	}

	public java.lang.String getNoticetype() {
		return get("noticetype");
	}

	public void setColumnid(java.lang.Integer columnid) {
		set("columnid", columnid);
	}

	public java.lang.Integer getColumnid() {
		return get("columnid");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}

	public java.lang.String getSummary() {
		return get("summary");
	}

	public void setSource(java.lang.String source) {
		set("source", source);
	}

	public java.lang.String getSource() {
		return get("source");
	}

	public void setIscomment(java.lang.String iscomment) {
		set("iscomment", iscomment);
	}

	public java.lang.String getIscomment() {
		return get("iscomment");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

	public java.lang.String getAuthor() {
		return get("author");
	}

	public void setThumb(java.lang.String thumb) {
		set("thumb", thumb);
	}

	public java.lang.String getThumb() {
		return get("thumb");
	}

	public void setSortno(java.lang.Integer sortno) {
		set("sortno", sortno);
	}

	public java.lang.Integer getSortno() {
		return get("sortno");
	}

	public void setHits(java.lang.Integer hits) {
		set("hits", hits);
	}

	public java.lang.Integer getHits() {
		return get("hits");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
