package com.tsjy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseModule<M extends BaseModule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setEnName(java.lang.String enName) {
		set("en_name", enName);
	}

	public java.lang.String getEnName() {
		return get("en_name");
	}

	public void setHomePage(java.lang.String homePage) {
		set("home_page", homePage);
	}

	public java.lang.String getHomePage() {
		return get("home_page");
	}

	public void setSortNo(java.lang.Integer sortNo) {
		set("sort_no", sortNo);
	}

	public java.lang.Integer getSortNo() {
		return get("sort_no");
	}

	public void setCollapsed(java.lang.String collapsed) {
		set("collapsed", collapsed);
	}

	public java.lang.String getCollapsed() {
		return get("collapsed");
	}

}
