package com.tsjy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseColumn<M extends BaseColumn<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

	public void setCustomId(java.lang.String customId) {
		set("custom_id", customId);
	}

	public java.lang.String getCustomId() {
		return get("custom_id");
	}

	public void setSortNo(java.lang.Integer sortNo) {
		set("sort_no", sortNo);
	}

	public java.lang.Integer getSortNo() {
		return get("sort_no");
	}

	public void setLeaf(java.lang.String leaf) {
		set("leaf", leaf);
	}

	public java.lang.String getLeaf() {
		return get("leaf");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setEnabled(java.lang.String enabled) {
		set("enabled", enabled);
	}

	public java.lang.String getEnabled() {
		return get("enabled");
	}

}
