package com.tsjy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleAuth<M extends BaseRoleAuth<M>> extends Model<M> implements IBean {

	public void setRoleId(java.lang.String roleId) {
		set("role_id", roleId);
	}

	public java.lang.String getRoleId() {
		return get("role_id");
	}

	public void setMenuId(java.lang.String menuId) {
		set("menu_id", menuId);
	}

	public java.lang.String getMenuId() {
		return get("menu_id");
	}

	public void setActions(java.lang.String actions) {
		set("actions", actions);
	}

	public java.lang.String getActions() {
		return get("actions");
	}

	public void setUi(java.lang.String ui) {
		set("ui", ui);
	}

	public java.lang.String getUi() {
		return get("ui");
	}

}
