package com.tsjy.model;

import com.tsjy.model.base.BaseColumn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Column extends BaseColumn<Column> {
	public static final Column dao = new Column();
}
