package com.tsjy.model;

import java.util.ArrayList;
import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.plat.core.dto.BaseDto;
import com.plat.core.dto.Dto;
import com.plat.core.util.TSUtils;
import com.tsjy.model.base.BaseDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dept extends BaseDept<Dept> {
	public static final Dept dao = new Dept();
	
	public void setParent_name(String parent_name) {
		set("parent_name", parent_name);
	}

	public String getParent_name() {

		return getStr("parent_name");
	}
	



	public List getDetpTreeList() {
		List<Record> list = Db
				.find("SELECT id,name text,parent_id pid,leaf FROM ts_dept where parent_id !=0 order by sort_no");

		List menuList = getSubNodes(list, "001");
		return menuList;
	}

	public List getSubNodes(List<Record> allNodes, String pid) {
		List subNodes = new ArrayList();

		for (Record item : allNodes) {
			if (pid.equals(item.getStr("pid"))) {
				Dto dto = new BaseDto();
				dto.put("id", item.getStr("id"));
				dto.put("leaf", item.getStr("leaf"));
				dto.put("pid", item.getStr("pid"));
				dto.put("text", item.getStr("text"));

				List children = getSubNodes(allNodes, item.getStr("id"));
				if (TSUtils.isNotEmpty(children)) {
					dto.put("children", children);
				}
				subNodes.add(dto);
			}
		}
		return subNodes;
	}
}
