package com.tsjy.model;

import com.tsjy.model.base.BaseIcon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Icon extends BaseIcon<Icon> {
	public static final Icon dao = new Icon();
}
