package com.tsjy.model;

import com.tsjy.model.base.BaseMenuAction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuAction extends BaseMenuAction<MenuAction> {
	public static final MenuAction dao = new MenuAction();
}
