package com.tsjy.model;

import java.util.List;

import com.plat.core.dto.BaseDto;
import com.plat.core.dto.Dto;
import com.tsjy.model.base.BaseModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Module extends BaseModule<Module> {
	public static final Module dao = new Module();
	
	public String getTree_num() {
		return getNumber("tree_num").toString();
	}


	public void setTree_num(String tree_num) {
		set("tree_num",tree_num);
	}


	/**
	 * 查询用户的授权菜单所属的模块
	 * 
	 * @param userid
	 * @return List<MenuModel>
	 */
	public List<Module> getAuthModuleList(String userid) {
		String sql = "select t.*, t1.tree_num " + " from ts_module t,"
				+ " (select m.module_id, count(1) tree_num"
				+ "    from ts_menu m, ts_role_auth r, ts_user_role u"
				+ "   where m.id = r.menu_id"
				+ "     and r.role_id = u.role_id" + "     and m.leaf = 0"
				+ "     and u.user_id = ?" + "   group by m.module_id) t1"
				+ " where t.id = t1.module_id";
		
		List<Module> modules = dao.find(sql, userid);

		return modules;
	}
	
	public List<Module> queryDatas(){
		
		
		return dao.find("select * from ts_module");
	}
	
	public Dto queryComboDatas(){
		
		List<Module> list = dao.find("select id,name from ts_module");
		
		Dto dto = new BaseDto();
		
		for (Module moduleModel : list) {
			dto.put(moduleModel.getNumber("id").toString(), moduleModel.getStr("name"));
		}
		
		return dto;
		
	}
}
