package com.tsjy.model;

import com.tsjy.model.base.BaseParam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Param extends BaseParam<Param> {
	public static final Param dao = new Param();
}
