package com.tsjy.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.tsjy.model.base.BaseRoleAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleAuth extends BaseRoleAuth<RoleAuth> {
	public static final RoleAuth dao = new RoleAuth();
	
	public List<RoleAuth> getAuthActionList(String userid) {

		String sql = "select a.actions from ts_user_role u,ts_role_auth a " +
				"where u.role_id = a.role_id and u.user_id=? and a.ACTIONS is not null";

		List<RoleAuth> actions = dao.find(sql, userid);

		return actions;
	}
	
	public List<Record> getAuthUiList(String userid) {

		String sql = "select distinct a.ui,m.en_name from ts_user_role u,ts_role_auth a,ts_menu m " +
				"where u.role_id = a.role_id and  a.menu_id = m.id and u.user_id=? and a.ui is not null";

		List<Record> actions = Db.find(sql, userid);

		return actions;
	}
}
