package com.tsjy.model;

import java.util.List;

import com.tsjy.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
	
	/**
	 * 获取用户的角色
	 * @param userid
	 * @return
	 */
	public List<Role> getAuthRoleList(String userid) {
		
		String sql = "select r.name from ts_user_role u,ts_role r where u.role_id = r.id and u.user_id  = ?";

		List<Role> roles = dao.find(sql, userid);

		return roles;
	}
}
