package com.tsjy.model;

import com.tsjy.model.base.BaseSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Setting extends BaseSetting<Setting> {
	public static final Setting dao = new Setting();
}
